# Site settings
title: 이지헌의 포트폴리오
email: f/mpzneqeg
url: https://easy-h.github.io
description: "안녕하세요.
          게임 프로그래머 이지헌 입니다.
          언제나 읽기 쉬운 코드를 작성하기 위해 노력하고 있습니다.
          \"프로그래머는 ‘NO’라고 말해선 안된다\"를 목표삼아 공부하고 있습니다."
keywords: "your keywords, separated by commas"
skills: 
  - name: "C"
    show: <p>C</p>
  - name: "C++"
    show: <p>C++</p>
  - name: "C#"
    show: <p>C#</p>
  - name: "java"
    show: <i class="fa-brands fa-fw fa-java"></i>
  - name: "unity"
    show: <i class="fa-brands fa-fw fa-unity"></i>
  - name: "unreal"
    show: <p>Unreal</p>
meta_author: Lee Ji-Heon

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6799fa #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Easy-H
  - title: soundcloud
    url: https://soundcloud.com/rbqlc80m6ycn
  - title: itch-io
    url: https://easy-h.itch.io/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: /:categories/:title

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
      values:
      permalink: ""
